server:
  port: 8082


spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/microservice
    username: postgres
    password: Dar@4311
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: HOTEL-SERVICE

  config:
    import: optional:configserver:http://localhost:8085

okta:
  oauth2:
    issuer: https://dev-92186112.okta.com/oauth2/default
    audience: api://default

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka